### ISSUE TITLE
PHP Warning: Module `<module>` already loaded in... 

### ISSUE THREAD

**Issue by drupol** [fossar/nix-phps#29]
Hi,

I'm using this package as a dependency of another one: [loophp/nix-shell](https://packagist.org/packages/loophp/nix-shell)

I'm having an issue when running `composer install`:

<details>

```
~/d/g/collection   $…  nix-shell /home/pol/dev/git/nix-shell/resources/dev/php74/                                                                                                                                                           
Linux x260 5.10.45 x86_64
 09:31:36  up 4 days  0:20,  1 user,  load average: 1.72, 1.70, 2.17
 impure  ~/d/g/collection   $…  composer install                                                                                                                                                                             php-7.4.20 
No composer.lock file present. Updating dependencies to latest instead of installing from lock file. See https://getcomposer.org/install for more information.
Loading composer repositories with package information
Updating dependencies
Lock file operations: 118 installs, 0 updates, 0 removals
  - Locking amphp/amp (v2.5.2)
  - Locking amphp/byte-stream (v1.8.1)
  - Locking amphp/parallel (v1.4.0)
  - Locking amphp/parallel-functions (v1.0.0)
  - Locking amphp/parser (v1.0.0)
  - Locking amphp/process (v1.1.1)
  - Locking amphp/serialization (v1.0.0)
  - Locking amphp/sync (v1.4.0)
  - Locking composer/package-versions-deprecated (1.11.99.2)
  - Locking composer/semver (3.2.5)
  - Locking composer/spdx-licenses (1.5.5)
  - Locking composer/xdebug-handler (2.0.1)
  - Locking dnoegel/php-xdg-base-dir (v0.1.1)
  - Locking doctrine/annotations (1.13.1)
  - Locking doctrine/collections (1.6.7)
  - Locking doctrine/instantiator (1.4.0)
  - Locking doctrine/lexer (1.2.1)
  - Locking drupol/php-conventions (5.0.4)
  - Locking drupol/phpcsfixer-configs-php (2.0.1)
  - Locking ergebnis/composer-normalize (2.15.0)
  - Locking ergebnis/json-normalizer (1.0.3)
  - Locking ergebnis/json-printer (3.1.1)
  - Locking ergebnis/license (1.1.0)
  - Locking felixfbecker/advanced-json-rpc (v3.2.1)
  - Locking felixfbecker/language-server-protocol (1.5.1)
  - Locking friends-of-phpspec/phpspec-code-coverage (v6.1.0)
  - Locking friendsofphp/php-cs-fixer (v3.0.0)
  - Locking friendsoftwig/twigcs (v5.0.0)
  - Locking gitonomy/gitlib (v1.2.3)
  - Locking guzzlehttp/guzzle (7.3.0)
  - Locking guzzlehttp/promises (1.4.1)
  - Locking guzzlehttp/psr7 (1.8.2)
  - Locking halaxa/json-machine (0.7.0)
  - Locking infection/abstract-testframework-adapter (0.3.1)
  - Locking infection/extension-installer (0.1.1)
  - Locking infection/include-interceptor (0.2.4)
  - Locking infection/infection (0.23.0)
  - Locking infection/phpspec-adapter (0.1.2)
  - Locking justinrainbow/json-schema (5.2.10)
  - Locking localheinz/diff (1.1.1)
  - Locking loophp/grumphp-license-task (1.0.5)
  - Locking maglnet/composer-require-checker (3.3.0)
  - Locking monolog/monolog (2.2.0)
  - Locking netresearch/jsonmapper (v4.0.0)
  - Locking nikic/php-parser (v4.10.5)
  - Locking ondram/ci-detector (3.5.1)
  - Locking openlss/lib-array2xml (1.0.0)
  - Locking opis/closure (3.6.2)
  - Locking php-cs-fixer/diff (v2.0.2)
  - Locking php-parallel-lint/php-parallel-lint (v1.3.0)
  - Locking phpdocumentor/reflection-common (2.2.0)
  - Locking phpdocumentor/reflection-docblock (5.2.2)
  - Locking phpdocumentor/type-resolver (1.4.0)
  - Locking phpro/grumphp (v1.3.3)
  - Locking phpspec/php-diff (v1.1.3)
  - Locking phpspec/phpspec (7.1.0)
  - Locking phpspec/prophecy (1.13.0)
  - Locking phpstan/extension-installer (1.1.0)
  - Locking phpstan/phpstan (0.12.90)
  - Locking phpstan/phpstan-deprecation-rules (0.12.6)
  - Locking phpstan/phpstan-strict-rules (0.12.9)
  - Locking phpunit/php-code-coverage (9.2.6)
  - Locking phpunit/php-file-iterator (3.0.5)
  - Locking phpunit/php-text-template (2.0.4)
  - Locking psr/cache (1.0.1)
  - Locking psr/container (1.1.1)
  - Locking psr/event-dispatcher (1.0.0)
  - Locking psr/http-client (1.0.1)
  - Locking psr/http-message (1.0.1)
  - Locking psr/log (1.1.4)
  - Locking ralouphie/getallheaders (3.0.3)
  - Locking sanmai/later (0.1.2)
  - Locking sanmai/pipeline (v5.1.0)
  - Locking sebastian/code-unit-reverse-lookup (2.0.3)
  - Locking sebastian/comparator (4.0.6)
  - Locking sebastian/complexity (2.0.2)
  - Locking sebastian/diff (4.0.4)
  - Locking sebastian/environment (5.1.3)
  - Locking sebastian/exporter (4.0.3)
  - Locking sebastian/lines-of-code (1.0.3)
  - Locking sebastian/recursion-context (4.0.4)
  - Locking sebastian/version (3.0.2)
  - Locking seld/jsonlint (1.8.3)
  - Locking squizlabs/php_codesniffer (3.6.0)
  - Locking symfony/cache (v5.3.0)
  - Locking symfony/cache-contracts (v2.4.0)
  - Locking symfony/config (v5.3.2)
  - Locking symfony/console (v5.3.2)
  - Locking symfony/dependency-injection (v5.3.2)
  - Locking symfony/deprecation-contracts (v2.4.0)
  - Locking symfony/dotenv (v5.3.0)
  - Locking symfony/event-dispatcher (v5.3.0)
  - Locking symfony/event-dispatcher-contracts (v2.4.0)
  - Locking symfony/filesystem (v5.3.0)
  - Locking symfony/finder (v5.3.0)
  - Locking symfony/http-client (v5.3.2)
  - Locking symfony/http-client-contracts (v2.4.0)
  - Locking symfony/options-resolver (v5.3.0)
  - Locking symfony/polyfill-ctype (v1.23.0)
  - Locking symfony/polyfill-intl-grapheme (v1.23.0)
  - Locking symfony/polyfill-intl-normalizer (v1.23.0)
  - Locking symfony/polyfill-mbstring (v1.23.0)
  - Locking symfony/polyfill-php72 (v1.23.0)
  - Locking symfony/polyfill-php73 (v1.23.0)
  - Locking symfony/polyfill-php80 (v1.23.0)
  - Locking symfony/polyfill-php81 (v1.23.0)
  - Locking symfony/process (v5.3.2)
  - Locking symfony/service-contracts (v2.4.0)
  - Locking symfony/stopwatch (v5.3.0)
  - Locking symfony/string (v5.3.2)
  - Locking symfony/var-exporter (v5.3.2)
  - Locking symfony/yaml (v5.3.2)
  - Locking thecodingmachine/safe (v1.3.3)
  - Locking theseer/tokenizer (1.2.0)
  - Locking vimeo/psalm (4.8.1)
  - Locking webmozart/assert (1.10.0)
  - Locking webmozart/glob (4.3.0)
  - Locking webmozart/path-util (2.3.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 118 installs, 0 updates, 0 removals
  - Installing composer/package-versions-deprecated (1.11.99.2): Extracting archive
  - Installing infection/extension-installer (0.1.1): Extracting archive
  - Installing amphp/parser (v1.0.0): Extracting archive
  - Installing amphp/amp (v2.5.2): Extracting archive
  - Installing amphp/byte-stream (v1.8.1): Extracting archive
  - Installing amphp/process (v1.1.1): Extracting archive
  - Installing amphp/serialization (v1.0.0): Extracting archive
  - Installing amphp/sync (v1.4.0): Extracting archive
  - Installing symfony/polyfill-ctype (v1.23.0): Extracting archive
  - Installing symfony/polyfill-php80 (v1.23.0): Extracting archive
  - Installing symfony/polyfill-mbstring (v1.23.0): Extracting archive
  - Installing symfony/polyfill-intl-normalizer (v1.23.0): Extracting archive
  - Installing symfony/polyfill-intl-grapheme (v1.23.0): Extracting archive
  - Installing symfony/string (v5.3.2): Extracting archive
  - Installing psr/container (1.1.1): Extracting archive
  - Installing symfony/service-contracts (v2.4.0): Extracting archive
  - Installing symfony/polyfill-php73 (v1.23.0): Extracting archive
  - Installing symfony/deprecation-contracts (v2.4.0): Extracting archive
  - Installing symfony/console (v5.3.2): Extracting archive
  - Installing psr/log (1.1.4): Extracting archive
  - Installing symfony/yaml (v5.3.2): Extracting archive
  - Installing phpstan/phpstan (0.12.90): Extracting archive
  - Installing phpstan/extension-installer (1.1.0): Extracting archive
  - Installing symfony/process (v5.3.2): Extracting archive
  - Installing symfony/options-resolver (v5.3.0): Extracting archive
  - Installing symfony/finder (v5.3.0): Extracting archive
  - Installing symfony/filesystem (v5.3.0): Extracting archive
  - Installing psr/event-dispatcher (1.0.0): Extracting archive
  - Installing symfony/event-dispatcher-contracts (v2.4.0): Extracting archive
  - Installing symfony/event-dispatcher (v5.3.0): Extracting archive
  - Installing symfony/dotenv (v5.3.0): Extracting archive
  - Installing symfony/dependency-injection (v5.3.2): Extracting archive
  - Installing symfony/polyfill-php81 (v1.23.0): Extracting archive
  - Installing symfony/config (v5.3.2): Extracting archive
  - Installing seld/jsonlint (1.8.3): Extracting archive
  - Installing opis/closure (3.6.2): Extracting archive
  - Installing ondram/ci-detector (3.5.1): Extracting archive
  - Installing monolog/monolog (2.2.0): Extracting archive
  - Installing gitonomy/gitlib (v1.2.3): Extracting archive
  - Installing doctrine/collections (1.6.7): Extracting archive
  - Installing amphp/parallel (v1.4.0): Extracting archive
  - Installing amphp/parallel-functions (v1.0.0): Extracting archive
  - Installing phpro/grumphp (v1.3.3): Extracting archive
  - Installing localheinz/diff (1.1.1): Extracting archive
  - Installing justinrainbow/json-schema (5.2.10): Extracting archive
  - Installing ergebnis/json-printer (3.1.1): Extracting archive
  - Installing ergebnis/json-normalizer (1.0.3): Extracting archive
  - Installing ergebnis/composer-normalize (2.15.0): Extracting archive
  - Installing doctrine/lexer (1.2.1): Extracting archive
  - Installing webmozart/assert (1.10.0): Extracting archive
  - Installing webmozart/path-util (2.3.0): Extracting archive
  - Installing sebastian/diff (4.0.4): Extracting archive
  - Installing openlss/lib-array2xml (1.0.0): Extracting archive
  - Installing nikic/php-parser (v4.10.5): Extracting archive
  - Installing netresearch/jsonmapper (v4.0.0): Extracting archive
  - Installing felixfbecker/language-server-protocol (1.5.1): Extracting archive
  - Installing phpdocumentor/reflection-common (2.2.0): Extracting archive
  - Installing phpdocumentor/type-resolver (1.4.0): Extracting archive
  - Installing phpdocumentor/reflection-docblock (5.2.2): Extracting archive
  - Installing felixfbecker/advanced-json-rpc (v3.2.1): Extracting archive
  - Installing dnoegel/php-xdg-base-dir (v0.1.1): Extracting archive
  - Installing composer/xdebug-handler (2.0.1): Extracting archive
  - Installing composer/semver (3.2.5): Extracting archive
  - Installing vimeo/psalm (4.8.1): Extracting archive
  - Installing squizlabs/php_codesniffer (3.6.0): Extracting archive
  - Installing phpstan/phpstan-deprecation-rules (0.12.6): Extracting archive
  - Installing php-parallel-lint/php-parallel-lint (v1.3.0): Extracting archive
  - Installing webmozart/glob (4.3.0): Extracting archive
  - Installing maglnet/composer-require-checker (3.3.0): Extracting archive
  - Installing ergebnis/license (1.1.0): Extracting archive
  - Installing composer/spdx-licenses (1.5.5): Extracting archive
  - Installing loophp/grumphp-license-task (1.0.5): Extracting archive
  - Installing friendsoftwig/twigcs (v5.0.0): Extracting archive
  - Installing symfony/stopwatch (v5.3.0): Extracting archive
  - Installing symfony/polyfill-php72 (v1.23.0): Extracting archive
  - Installing php-cs-fixer/diff (v2.0.2): Extracting archive
  - Installing psr/cache (1.0.1): Extracting archive
  - Installing doctrine/annotations (1.13.1): Extracting archive
  - Installing friendsofphp/php-cs-fixer (v3.0.0): Extracting archive
  - Installing drupol/phpcsfixer-configs-php (2.0.1): Extracting archive
  - Installing drupol/php-conventions (5.0.4): Extracting archive
  - Installing theseer/tokenizer (1.2.0): Extracting archive
  - Installing sebastian/version (3.0.2): Extracting archive
  - Installing sebastian/lines-of-code (1.0.3): Extracting archive
  - Installing sebastian/environment (5.1.3): Extracting archive
  - Installing sebastian/complexity (2.0.2): Extracting archive
  - Installing sebastian/code-unit-reverse-lookup (2.0.3): Extracting archive
  - Installing phpunit/php-text-template (2.0.4): Extracting archive
  - Installing phpunit/php-file-iterator (3.0.5): Extracting archive
  - Installing phpunit/php-code-coverage (9.2.6): Extracting archive
  - Installing sebastian/recursion-context (4.0.4): Extracting archive
  - Installing sebastian/exporter (4.0.3): Extracting archive
  - Installing sebastian/comparator (4.0.6): Extracting archive
  - Installing doctrine/instantiator (1.4.0): Extracting archive
  - Installing phpspec/prophecy (1.13.0): Extracting archive
  - Installing phpspec/php-diff (v1.1.3): Extracting archive
  - Installing phpspec/phpspec (7.1.0): Extracting archive
  - Installing friends-of-phpspec/phpspec-code-coverage (v6.1.0): Extracting archive
  - Installing psr/http-message (1.0.1): Extracting archive
  - Installing psr/http-client (1.0.1): Extracting archive
  - Installing ralouphie/getallheaders (3.0.3): Extracting archive
  - Installing guzzlehttp/psr7 (1.8.2): Extracting archive
  - Installing guzzlehttp/promises (1.4.1): Extracting archive
  - Installing guzzlehttp/guzzle (7.3.0): Extracting archive
  - Installing halaxa/json-machine (0.7.0): Extracting archive
  - Installing thecodingmachine/safe (v1.3.3): Extracting archive
  - Installing sanmai/pipeline (v5.1.0): Extracting archive
  - Installing sanmai/later (0.1.2): Extracting archive
  - Installing infection/include-interceptor (0.2.4): Extracting archive
  - Installing infection/abstract-testframework-adapter (0.3.1): Extracting archive
  - Installing infection/infection (0.23.0): Extracting archive
  - Installing infection/phpspec-adapter (0.1.2): Extracting archive
  - Installing phpstan/phpstan-strict-rules (0.12.9): Extracting archive
  - Installing symfony/var-exporter (v5.3.2): Extracting archive
  - Installing symfony/cache-contracts (v2.4.0): Extracting archive
  - Installing symfony/cache (v5.3.0): Extracting archive
  - Installing symfony/http-client-contracts (v2.4.0): Extracting archive
  - Installing symfony/http-client (v5.3.2): Extracting archive
40 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
69 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
infection/extension-installer: Extensions installed
> infection/phpspec-adapter: installed
phpstan/extension-installer: Extensions installed
> phpstan/phpstan-deprecation-rules: installed
> phpstan/phpstan-strict-rules: installed
Cannot load Zend OPcache - it was already loaded
Cannot load Xdebug - it was already loaded
Cannot load Zend OPcache - it was already loaded
Cannot load Xdebug - it was already loaded
PHP Warning:  Module 'filter' already loaded in Unknown on line 0
PHP Warning:  Module 'iconv' already loaded in Unknown on line 0
PHP Warning:  Module 'ctype' already loaded in Unknown on line 0
PHP Warning:  Module 'session' already loaded in Unknown on line 0
PHP Warning:  Module 'json' already loaded in Unknown on line 0
PHP Warning:  Module 'redis' already loaded in Unknown on line 0
PHP Warning:  Module 'tokenizer' already loaded in Unknown on line 0
PHP Warning:  Module 'SimpleXML' already loaded in Unknown on line 0
PHP Warning:  Module 'dom' already loaded in Unknown on line 0
PHP Warning:  Module 'posix' already loaded in Unknown on line 0
PHP Warning:  Module 'intl' already loaded in Unknown on line 0
PHP Warning:  Module 'calendar' already loaded in Unknown on line 0
PHP Warning:  Module 'curl' already loaded in Unknown on line 0
PHP Warning:  Module 'exif' already loaded in Unknown on line 0
PHP Warning:  Module 'fileinfo' already loaded in Unknown on line 0
PHP Warning:  Module 'gd' already loaded in Unknown on line 0
PHP Warning:  Module 'mbstring' already loaded in Unknown on line 0
PHP Warning:  Module 'openssl' already loaded in Unknown on line 0
PHP Warning:  Module 'pcov' already loaded in Unknown on line 0
PHP Warning:  Module 'PDO' already loaded in Unknown on line 0
PHP Warning:  Module 'pdo_sqlite' already loaded in Unknown on line 0
PHP Warning:  Module 'mysqlnd' already loaded in Unknown on line 0
PHP Warning:  Module 'pdo_mysql' already loaded in Unknown on line 0
PHP Warning:  Module 'pdo_pgsql' already loaded in Unknown on line 0
PHP Warning:  Module 'soap' already loaded in Unknown on line 0
PHP Warning:  Module 'xmlreader' already loaded in Unknown on line 0
PHP Warning:  Module 'xmlwriter' already loaded in Unknown on line 0
PHP Warning:  Module 'zip' already loaded in Unknown on line 0
PHP Warning:  Module 'zlib' already loaded in Unknown on line 0
PHP Warning:  Module 'filter' already loaded in Unknown on line 0
PHP Warning:  Module 'iconv' already loaded in Unknown on line 0
PHP Warning:  Module 'ctype' already loaded in Unknown on line 0
PHP Warning:  Module 'session' already loaded in Unknown on line 0
PHP Warning:  Module 'json' already loaded in Unknown on line 0
PHP Warning:  Module 'redis' already loaded in Unknown on line 0
PHP Warning:  Module 'tokenizer' already loaded in Unknown on line 0
PHP Warning:  Module 'SimpleXML' already loaded in Unknown on line 0
PHP Warning:  Module 'dom' already loaded in Unknown on line 0
PHP Warning:  Module 'posix' already loaded in Unknown on line 0
PHP Warning:  Module 'intl' already loaded in Unknown on line 0
PHP Warning:  Module 'calendar' already loaded in Unknown on line 0
PHP Warning:  Module 'curl' already loaded in Unknown on line 0
PHP Warning:  Module 'exif' already loaded in Unknown on line 0
PHP Warning:  Module 'fileinfo' already loaded in Unknown on line 0
PHP Warning:  Module 'gd' already loaded in Unknown on line 0
PHP Warning:  Module 'mbstring' already loaded in Unknown on line 0
PHP Warning:  Module 'openssl' already loaded in Unknown on line 0
PHP Warning:  Module 'pcov' already loaded in Unknown on line 0
PHP Warning:  Module 'PDO' already loaded in Unknown on line 0
PHP Warning:  Module 'pdo_sqlite' already loaded in Unknown on line 0
PHP Warning:  Module 'mysqlnd' already loaded in Unknown on line 0
PHP Warning:  Module 'pdo_mysql' already loaded in Unknown on line 0
PHP Warning:  Module 'pdo_pgsql' already loaded in Unknown on line 0
PHP Warning:  Module 'soap' already loaded in Unknown on line 0
PHP Warning:  Module 'xmlreader' already loaded in Unknown on line 0
PHP Warning:  Module 'xmlwriter' already loaded in Unknown on line 0
PHP Warning:  Module 'zip' already loaded in Unknown on line 0
PHP Warning:  Module 'zlib' already loaded in Unknown on line 0
Cannot load Zend OPcache - it was already loaded
Cannot load Xdebug - it was already loaded
Cannot load Zend OPcache - it was already loaded
Cannot load Xdebug - it was already loaded
PHP Warning:  Module 'filter' already loaded in Unknown on line 0
PHP Warning:  Module 'iconv' already loaded in Unknown on line 0
PHP Warning:  Module 'ctype' already loaded in Unknown on line 0
PHP Warning:  Module 'session' already loaded in Unknown on line 0
PHP Warning:  Module 'json' already loaded in Unknown on line 0
PHP Warning:  Module 'redis' already loaded in Unknown on line 0
PHP Warning:  Module 'tokenizer' already loaded in Unknown on line 0
PHP Warning:  Module 'SimpleXML' already loaded in Unknown on line 0
PHP Warning:  Module 'dom' already loaded in Unknown on line 0
PHP Warning:  Module 'posix' already loaded in Unknown on line 0
PHP Warning:  Module 'intl' already loaded in Unknown on line 0
PHP Warning:  Module 'calendar' already loaded in Unknown on line 0
PHP Warning:  Module 'curl' already loaded in Unknown on line 0
PHP Warning:  Module 'exif' already loaded in Unknown on line 0
PHP Warning:  Module 'fileinfo' already loaded in Unknown on line 0
PHP Warning:  Module 'gd' already loaded in Unknown on line 0
PHP Warning:  Module 'mbstring' already loaded in Unknown on line 0
PHP Warning:  Module 'openssl' already loaded in Unknown on line 0
PHP Warning:  Module 'pcov' already loaded in Unknown on line 0
PHP Warning:  Module 'PDO' already loaded in Unknown on line 0
PHP Warning:  Module 'pdo_sqlite' already loaded in Unknown on line 0
PHP Warning:  Module 'mysqlnd' already loaded in Unknown on line 0
PHP Warning:  Module 'pdo_mysql' already loaded in Unknown on line 0
PHP Warning:  Module 'pdo_pgsql' already loaded in Unknown on line 0
PHP Warning:  Module 'soap' already loaded in Unknown on line 0
PHP Warning:  Module 'xmlreader' already loaded in Unknown on line 0
PHP Warning:  Module 'xmlwriter' already loaded in Unknown on line 0
PHP Warning:  Module 'zip' already loaded in Unknown on line 0
PHP Warning:  Module 'zlib' already loaded in Unknown on line 0
PHP Warning:  Module 'filter' already loaded in Unknown on line 0
PHP Warning:  Module 'iconv' already loaded in Unknown on line 0
PHP Warning:  Module 'ctype' already loaded in Unknown on line 0
PHP Warning:  Module 'session' already loaded in Unknown on line 0
PHP Warning:  Module 'json' already loaded in Unknown on line 0
PHP Warning:  Module 'redis' already loaded in Unknown on line 0
PHP Warning:  Module 'tokenizer' already loaded in Unknown on line 0
PHP Warning:  Module 'SimpleXML' already loaded in Unknown on line 0
PHP Warning:  Module 'dom' already loaded in Unknown on line 0
PHP Warning:  Module 'posix' already loaded in Unknown on line 0
PHP Warning:  Module 'intl' already loaded in Unknown on line 0
PHP Warning:  Module 'calendar' already loaded in Unknown on line 0
PHP Warning:  Module 'curl' already loaded in Unknown on line 0
PHP Warning:  Module 'exif' already loaded in Unknown on line 0
PHP Warning:  Module 'fileinfo' already loaded in Unknown on line 0
PHP Warning:  Module 'gd' already loaded in Unknown on line 0
PHP Warning:  Module 'mbstring' already loaded in Unknown on line 0
PHP Warning:  Module 'openssl' already loaded in Unknown on line 0
PHP Warning:  Module 'pcov' already loaded in Unknown on line 0
PHP Warning:  Module 'PDO' already loaded in Unknown on line 0
PHP Warning:  Module 'pdo_sqlite' already loaded in Unknown on line 0
PHP Warning:  Module 'mysqlnd' already loaded in Unknown on line 0
PHP Warning:  Module 'pdo_mysql' already loaded in Unknown on line 0
PHP Warning:  Module 'pdo_pgsql' already loaded in Unknown on line 0
PHP Warning:  Module 'soap' already loaded in Unknown on line 0
PHP Warning:  Module 'xmlreader' already loaded in Unknown on line 0
PHP Warning:  Module 'xmlwriter' already loaded in Unknown on line 0
PHP Warning:  Module 'zip' already loaded in Unknown on line 0
PHP Warning:  Module 'zlib' already loaded in Unknown on line 0
Watch out! GrumPHP is sniffing your commits!
 impure  ~/d/g/collection   $… 
```

</details>

This is an issue that I already had when using the default Nix package, see [#125405](https://github.com/NixOS/nixpkgs/pull/125405). It has been reverted since.

**Comment by jtojnar** [comment]
This is fixed in https://github.com/fossar/nix-phps/commit/523c84ce0f4699ba337069e15b4ded80b3d74363.

Compare:

- https://github.com/NixOS/nixpkgs/blob/e85975942742a3728226ac22a3415f2355bfc897/pkgs/development/interpreters/php/generic.nix
- https://github.com/NixOS/nixpkgs/blob/0747387223edf1aa5beaedf48983471315d95e16/pkgs/development/interpreters/php/generic.nix

**Comment by drupol** [comment]
Then the issue is still present locally. Should I do something to upgrade my local stack?

**Comment by jtojnar** [comment]
Yes, you need to update your [pinned version](https://github.com/loophp/nix-shell/blob/5ec6f37059923bfcaed02d8aba5d2cbf10bf2298/resources/dev/common.nix#L3) to that commit.

**Comment by drupol** [comment]
Indeed, thank you very much !!!

I will investigate niv.

**Comment by jtojnar** [comment]
I have added an example to readme:

https://github.com/fossar/nix-phps#with-niv
